version: "3.8"
services:
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: eduquiz
      MYSQL_USER: eduquiz
      MYSQL_PASSWORD: change_me
      MYSQL_ROOT_PASSWORD: root_pw_change_me
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: ["--default-authentication-plugin=mysql_native_password"]

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root_pw_change_me
    depends_on:
      - db

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_URL: jdbc:mysql://db:3306/eduquiz?useSSL=false&serverTimezone=UTC
      DB_USER: eduquiz
      DB_PASS: change_me

volumes:
  mysql_data:
